name: pip
channels:
  - anaconda
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.4
  - archspec=0.2.1
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.13.1
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - bleach=6.1.0
  - boltons=23.0.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - conda=23.10.0
  - conda-libmamba-solver=23.11.1
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - cryptography=41.0.3
  - cuda-cudart=12.3.101
  - cuda-nvrtc=12.3.103
  - cuda-python=12.2.0
  - cudatoolkit=11.8.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - fmt=9.1.0
  - fqdn=1.5.1
  - icu=73.2
  - idna=3.6
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.1.1
  - ipykernel=5.5.5
  - ipython=8.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.2
  - json5=0.9.14
  - jsonpointer=2.4
  - jsonschema=4.20.0
  - jsonschema-specifications=2023.11.1
  - jsonschema-with-format-nongpl=4.20.0
  - jupyter-lsp=2.2.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jupyter_events=0.9.0
  - jupyter_server=2.11.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.9
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.25.2
  - jupyterlab_widgets=3.0.9
  - krb5=1.20.1
  - ld_impl_linux-64=2.38
  - libarchive=3.6.2
  - libblas=3.9.0
  - libboost=1.82.0
  - libboost-python=1.82.0
  - libcblas=3.9.0
  - libcurl=8.4.0
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - libmamba=1.5.3
  - libmambapy=1.5.3
  - libnghttp2=1.57.0
  - libopenblas=0.3.25
  - libsodium=1.0.18
  - libsolv=0.7.24
  - libssh2=1.10.0
  - libstdcxx-ng=13.2.0
  - libxml2=2.10.4
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - mako=1.3.0
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=3.0.2
  - nbclient=0.8.0
  - nbconvert-core=7.11.0
  - nbformat=5.9.2
  - ncurses=6.4
  - notebook-shim=0.2.3
  - numpy=1.24.4
  - openssl=3.0.12
  - overrides=7.4.0
  - packaging=23.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.0.0
  - pluggy=1.0.0
  - prometheus_client=0.19.0
  - prompt-toolkit=3.0.41
  - prompt_toolkit=3.0.41
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pycuda=2023.1
  - pygments=2.17.2
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.8.18
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.0
  - python-json-logger=2.0.7
  - python_abi=3.8
  - pytools=2023.1.1
  - pytz=2023.3.post1
  - pyyaml=6.0
  - pyzmq=25.1.0
  - readline=8.2
  - referencing=0.31.1
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - send2trash=1.8.2
  - setuptools=68.0.0
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.6.2
  - terminado=0.18.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.3.3
  - traitlets=5.14.0
  - types-python-dateutil=2.8.19.14
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - typing_utils=0.1.0
  - uri-template=1.3.0
  - wcwidth=0.2.12
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.6.4
  - wheel=0.41.2
  - widgetsnbextension=4.0.5
  - xz=5.4.2
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.5
  - pip:
      - absl-py==2.0.0
      - accelerate==0.24.1
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - altair==5.2.0
      - annotated-types==0.6.0
      - anyio==3.7.1
      - asgiref==3.7.2
      - async-timeout==4.0.3
      - backoff==2.2.1
      - backports-zoneinfo==0.2.1
      - bcrypt==4.1.1
      - blinker==1.7.0
      - cachetools==5.3.2
      - chardet==5.2.0
      - chroma-hnswlib==0.7.3
      - chromadb==0.4.18
      - click==8.1.7
      - coloredlogs==15.0.1
      - dataclasses-json==0.6.3
      - datasets==2.15.0
      - deprecated==1.2.14
      - dill==0.3.7
      - distro==1.8.0
      - emoji==2.8.0
      - evaluate==0.4.0
      - fastapi==0.104.1
      - filelock==3.13.1
      - filetype==1.2.0
      - flatbuffers==23.5.26
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-auth==2.23.4
      - googleapis-common-protos==1.61.0
      - graphlib-backport==1.0.3
      - greenlet==3.0.1
      - grpcio==1.59.3
      - h11==0.14.0
      - httpcore==1.0.2
      - httptools==0.6.1
      - httpx==0.25.2
      - huggingface-hub==0.19.4
      - humanfriendly==10.0
      - joblib==1.3.2
      - jsonpatch==1.33
      - kubernetes==28.1.0
      - langchain==0.0.343
      - langchain-core==0.0.7
      - langdetect==1.0.9
      - langsmith==0.0.67
      - loralib==0.1.1
      - lxml==4.9.3
      - markdown-it-py==3.0.0
      - marshmallow==3.20.1
      - mdurl==0.1.2
      - mmh3==4.0.1
      - monotonic==1.6
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.15
      - mypy-extensions==1.0.0
      - networkx==3.1
      - nltk==3.8.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - onnxruntime==1.16.3
      - openai==1.3.6
      - opentelemetry-api==1.21.0
      - opentelemetry-exporter-otlp-proto-common==1.21.0
      - opentelemetry-exporter-otlp-proto-grpc==1.21.0
      - opentelemetry-instrumentation==0.42b0
      - opentelemetry-instrumentation-asgi==0.42b0
      - opentelemetry-instrumentation-fastapi==0.42b0
      - opentelemetry-proto==1.21.0
      - opentelemetry-sdk==1.21.0
      - opentelemetry-semantic-conventions==0.42b0
      - opentelemetry-util-http==0.42b0
      - pandas==2.0.3
      - peft==0.3.0
      - pillow==10.1.0
      - posthog==3.0.2
      - protobuf==4.25.1
      - psutil==5.9.6
      - pulsar-client==3.3.0
      - pyarrow==14.0.1
      - pyarrow-hotfix==0.6
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pydantic==2.5.2
      - pydantic-core==2.14.5
      - pydeck==0.8.1b0
      - pypika==0.48.9
      - python-dotenv==1.0.0
      - python-iso639==2023.6.15
      - python-magic==0.4.27
      - rapidfuzz==3.5.2
      - regex==2023.10.3
      - requests-oauthlib==1.3.1
      - responses==0.18.0
      - rich==13.7.0
      - rouge-score==0.1.2
      - rsa==4.9
      - safetensors==0.4.1
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - smmap==5.0.1
      - sqlalchemy==2.0.23
      - starlette==0.27.0
      - streamlit==1.28.2
      - sympy==1.12
      - tabulate==0.9.0
      - tenacity==8.2.3
      - threadpoolctl==3.2.0
      - tokenizers==0.15.0
      - toml==0.10.2
      - toolz==0.12.0
      - torch==2.1.1
      - torchdata==0.7.1
      - torchvision==0.16.1
      - tqdm==4.66.1
      - transformers==4.35.2
      - triton==2.1.0
      - typer==0.9.0
      - typing-inspect==0.9.0
      - tzdata==2023.3
      - tzlocal==5.2
      - unstructured==0.11.2
      - urllib3==1.26.18
      - uvicorn==0.24.0.post1
      - uvloop==0.19.0
      - validators==0.22.0
      - watchdog==3.0.0
      - watchfiles==0.21.0
      - websockets==12.0
      - wrapt==1.16.0
      - xxhash==3.4.1
      - yarl==1.9.3
